Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'

Style/SpecialGlobalVars:
  Enabled: true
  Exclude:
    - 'bin/**/*'

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - 'bin/**/*'

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
    - 'bin/**/*'

Layout/EmptyLineAfterGuardClause:
  Enabled: true
  Exclude:
    - 'bin/**/*'

Style/IfUnlessModifier:
  Enabled: true
  Exclude:
    - 'bin/**/*'

Style/PerlBackrefs:
  Enabled: true
  Exclude:
    - 'bin/**/*'

Style/ExpandPathArguments:
  Enabled: true
  Exclude:
    - 'bin/**/*'

Layout/MultilineOperationIndentation:
  Enabled: true
  Exclude:
    - 'bin/**/*'
