default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASS") { 'postgres' } %>

development:
  <<: *default
  database: quest_custom_ror_development

test:
  <<: *default
  database: quest_custom_ror_test
  host: 127.0.0.1

production:
  <<: *default
  database: quest_custom_ror_production
  username: quest_custom_ror
  password: <%= ENV['QUEST_CUSTOM_ROR_DATABASE_PASSWORD'] %>
